version: "3"
services:
  billing:
    build: billing/
    container_name: billing
    ports:
      - "3000:3000"
    volumes:
      - ./billing:/opt/billing
      - /opt/billing/node_modules
    depends_on:
      - "postgresql"
    environment:
      - POSTGRES_PASSWORD=postgres
    command: ["./wait-for-postgres.sh", "postgresql", "yarn", "start:dev"]
  postgresql:
    image: postgres:13.3-alpine
    container_name: postgresql
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
